include: package:lint/analysis_options.yaml
analyzer:
  strong-mode:
    # Will become the default once non-nullable types land
    # https://github.com/dart-lang/sdk/issues/31410#issuecomment-510683629
    implicit-casts: true
    implicit-dynamic: true